#!/bin/bash
# mbrola crashes on exit() cleanup, so don't bother trying to exit cleanly,
# mbrola does close the output file fine anyway (see #856331)
LD_PRELOAD=$SNAP/usr/lib/x86_64-linux-gnu/mbrola/libstrongexit.so exec $SNAP/usr/lib/x86_64-linux-gnu/mbrola/mbrola "$@"
